# Generated by Django 4.2.11 on 2025-12-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('water_tanks', 'Water Tanks & Storage'), ('sanitation', 'Sanitation'), ('agriculture', 'Agriculture'), ('material_handling', 'Material Handling'), ('water_supply', 'Water Supply & Accessories'), ('special_products', 'Special Products')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('viable', 'Viable'), ('simple', 'Simple')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
