# Generated by Django 4.2.11 on 2025-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.BooleanField(default=True),
        ),
    ]
