# Generated by Django 4.2.11 on 2025-12-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
    model_name='product',
    name='slug',
    field=models.SlugField(blank=True, null=True),  # remove unique=True
)
]
