# Generated by Django 4.2.11 on 2025-12-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief summary shown on product cards or listings.', max_length=300, null=True),
        ),
    ]
