# Generated by Django 4.2.11 on 2025-12-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_shippingzone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingZone',
        ),
    ]
