# Generated by Django 4.2.11 on 2025-12-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_shippingzone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingZone',
            new_name='Shipping',
        ),
    ]
