# Generated by Django 4.2.11 on 2025-12-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_shippingzone_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
