# Generated by Django 4.2.11 on 2025-12-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_productoption_stock_delete_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.FileField(blank=True, help_text='Upload product brochure (PDF recommended)', null=True, upload_to='brochures/'),
        ),
    ]
