# Generated by Django 4.2.11 on 2025-12-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_productfeature_productapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productapplication',
            name='text',
        ),
        migrations.AddField(
            model_name='productapplication',
            name='application1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='application2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='application3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='application4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='application5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='application6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='application7',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
