# Generated by Django 4.2.11 on 2025-12-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_productapplication_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productapplication',
            name='application1',
        ),
        migrations.RemoveField(
            model_name='productapplication',
            name='application2',
        ),
        migrations.RemoveField(
            model_name='productapplication',
            name='application3',
        ),
        migrations.RemoveField(
            model_name='productapplication',
            name='application4',
        ),
        migrations.RemoveField(
            model_name='productapplication',
            name='application5',
        ),
        migrations.RemoveField(
            model_name='productapplication',
            name='application6',
        ),
        migrations.RemoveField(
            model_name='productapplication',
            name='application7',
        ),
        migrations.AddField(
            model_name='productapplication',
            name='text',
            field=models.CharField(default=111, max_length=255),
            preserve_default=False,
        ),
    ]
