# Generated by Django 4.2.11 on 2025-12-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_productapplication_application1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offers_delivery',
            field=models.BooleanField(default=False, help_text='Check this if this product requires delivery & shipping zone selection'),
        ),
    ]
