# Generated by Django 4.2.11 on 2025-12-31 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_cartitem_unique_together_cartitem_option_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productoption'),
        ),
    ]
