# Generated by Django 4.2.11 on 2025-12-31 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0027_cartitem_option'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product', 'option')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='option_label',
        ),
    ]
