# Generated by Django 4.2.11 on 2026-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this size/option', upload_to='products/options/'),
        ),
    ]
