# Generated by Django 4.2.11 on 2026-01-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
