# Generated by Django 4.2.11 on 2026-02-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_orderitem_remove_order_billing_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
