# Generated by Django 4.2.11 on 2026-02-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shipping_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
